# Generated by Django 3.2.4 on 2021-06-17 11:45

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='section1',
            field=wagtail.core.fields.StreamField([('head1', wagtail.core.blocks.RichTextBlock()), ('head2', wagtail.core.blocks.RichTextBlock()), ('head3', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock())], blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='section10',
            field=wagtail.core.fields.StreamField([], blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='section11',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.RichTextBlock()), ('cards', wagtail.core.blocks.ListBlock(wagtail.images.blocks.ImageChooserBlock()))], blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='section12',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.RichTextBlock())], blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='section13',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.RichTextBlock())], blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='section14',
            field=wagtail.core.fields.StreamField([('title', wagtail.core.blocks.RichTextBlock())], blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='section2',
            field=wagtail.core.fields.StreamField([('head1', wagtail.core.blocks.RichTextBlock()), ('head2', wagtail.core.blocks.RichTextBlock()), ('text', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock())], blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='section3',
            field=wagtail.core.fields.StreamField([], blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='section4',
            field=wagtail.core.fields.StreamField([], blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='section5',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.RichTextBlock())], blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='section6',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.RichTextBlock())], blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='section7',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.RichTextBlock()), ('st1', wagtail.core.blocks.RichTextBlock()), ('sc1', wagtail.core.blocks.RichTextBlock()), ('st2', wagtail.core.blocks.RichTextBlock()), ('sc2', wagtail.core.blocks.RichTextBlock()), ('st3', wagtail.core.blocks.RichTextBlock()), ('sc3', wagtail.core.blocks.RichTextBlock())], blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='section8',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.RichTextBlock()), ('text', wagtail.core.blocks.RichTextBlock())], blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='section9',
            field=wagtail.core.fields.StreamField([('title', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock())], blank=True, null=True),
        ),
    ]
