# Generated by Django 3.2.4 on 2021-06-17 17:29

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210617_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='section10',
            field=wagtail.core.fields.StreamField([('content', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.RichTextBlock(help_text='Title here', required=False)), ('text', wagtail.core.blocks.RichTextBlock(help_text='Text here', required=False)), ('image', wagtail.images.blocks.ImageChooserBlock(help_text='Image here', required=False))]))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='section12',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.RichTextBlock()), ('contents', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.RichTextBlock(help_text='Title here', required=False)), ('text', wagtail.core.blocks.RichTextBlock(help_text='Text here', required=False)), ('image', wagtail.images.blocks.ImageChooserBlock(help_text='Image here', required=False))])))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='section13',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.RichTextBlock()), ('cards', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.RichTextBlock(help_text='Title here', required=False)), ('text', wagtail.core.blocks.RichTextBlock(help_text='Text here', required=False)), ('image', wagtail.images.blocks.ImageChooserBlock(help_text='Image here', required=False))])))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='section2',
            field=wagtail.core.fields.StreamField([('head1', wagtail.core.blocks.RichTextBlock()), ('head2', wagtail.core.blocks.RichTextBlock()), ('text', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('cta', wagtail.core.blocks.PageChooserBlock())], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='section3',
            field=wagtail.core.fields.StreamField([('cards', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.RichTextBlock(help_text='Title here', required=False)), ('text', wagtail.core.blocks.RichTextBlock(help_text='Text here', required=False)), ('image', wagtail.images.blocks.ImageChooserBlock(help_text='Image here', required=False)), ('cta', wagtail.core.blocks.PageChooserBlock())])))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='section4',
            field=wagtail.core.fields.StreamField([('content', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.RichTextBlock(help_text='Title here', required=False)), ('text', wagtail.core.blocks.RichTextBlock(help_text='Text here', required=False)), ('image', wagtail.images.blocks.ImageChooserBlock(help_text='Image here', required=False)), ('cta', wagtail.core.blocks.PageChooserBlock())]))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='section5',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.RichTextBlock()), ('cards', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.RichTextBlock(help_text='Title here', required=False)), ('text', wagtail.core.blocks.RichTextBlock(help_text='Text here', required=False)), ('image', wagtail.images.blocks.ImageChooserBlock(help_text='Image here', required=False))])))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='section6',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.RichTextBlock()), ('cards', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.RichTextBlock(help_text='Title here', required=False)), ('text', wagtail.core.blocks.RichTextBlock(help_text='Text here', required=False)), ('image', wagtail.images.blocks.ImageChooserBlock(help_text='Image here', required=False))])))], blank=True, null=True),
        ),
    ]
