# Generated by Django 3.2.4 on 2021-07-07 09:39

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210617_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='section1',
            field=wagtail.core.fields.StreamField([('heading1', wagtail.core.blocks.CharBlock()), ('heading2', wagtail.core.blocks.CharBlock()), ('info_line', wagtail.core.blocks.CharBlock()), ('image', wagtail.images.blocks.ImageChooserBlock())], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='section10',
            field=wagtail.core.fields.StreamField([('heading1', wagtail.core.blocks.CharBlock()), ('heading2', wagtail.core.blocks.CharBlock()), ('info_line', wagtail.core.blocks.CharBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('cta', wagtail.core.blocks.StructBlock([('button_page', wagtail.core.blocks.PageChooserBlock()), ('button_text', wagtail.core.blocks.CharBlock())]))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='section11',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock()), ('cards', wagtail.images.blocks.ImageChooserBlock())], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='section12',
            field=wagtail.core.fields.StreamField([], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='section13',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock()), ('reviews', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('review', wagtail.core.blocks.TextBlock()), ('person_image', wagtail.images.blocks.ImageChooserBlock()), ('person_name', wagtail.core.blocks.CharBlock()), ('person_info', wagtail.core.blocks.CharBlock())])))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='section14',
            field=wagtail.core.fields.StreamField([('heading1', wagtail.core.blocks.CharBlock()), ('heading2', wagtail.core.blocks.CharBlock()), ('cta', wagtail.core.blocks.StructBlock([('button_page', wagtail.core.blocks.PageChooserBlock()), ('button_text', wagtail.core.blocks.CharBlock())]))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='section2',
            field=wagtail.core.fields.StreamField([('heading1', wagtail.core.blocks.CharBlock()), ('heading2', wagtail.core.blocks.CharBlock()), ('info_line', wagtail.core.blocks.RichTextBlock()), ('cta', wagtail.core.blocks.StructBlock([('button_page', wagtail.core.blocks.PageChooserBlock()), ('button_text', wagtail.core.blocks.CharBlock())]))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='section3',
            field=wagtail.core.fields.StreamField([('cards', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock()), ('text', wagtail.core.blocks.TextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('cta', wagtail.core.blocks.StructBlock([('button_page', wagtail.core.blocks.PageChooserBlock()), ('button_text', wagtail.core.blocks.CharBlock())]))])))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='section4',
            field=wagtail.core.fields.StreamField([('heading1', wagtail.core.blocks.CharBlock()), ('heading2', wagtail.core.blocks.CharBlock()), ('text_info', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('cta', wagtail.core.blocks.StructBlock([('button_page', wagtail.core.blocks.PageChooserBlock()), ('button_text', wagtail.core.blocks.CharBlock())]))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='section5',
            field=wagtail.core.fields.StreamField([('heading1', wagtail.core.blocks.CharBlock()), ('heading2', wagtail.core.blocks.CharBlock()), ('cards', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('logo', wagtail.core.blocks.CharBlock()), ('title', wagtail.core.blocks.CharBlock()), ('text', wagtail.core.blocks.CharBlock())])))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='section6',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock()), ('cards', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('number', wagtail.core.blocks.IntegerBlock()), ('title', wagtail.core.blocks.CharBlock()), ('text', wagtail.core.blocks.TextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock())])))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='section7',
            field=wagtail.core.fields.StreamField([('heading1', wagtail.core.blocks.CharBlock()), ('heading2', wagtail.core.blocks.CharBlock()), ('cards', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock()), ('text', wagtail.core.blocks.CharBlock())])))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='section8',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock()), ('text_info', wagtail.core.blocks.TextBlock()), ('ext_url', wagtail.core.blocks.URLBlock())], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='section9',
            field=wagtail.core.fields.StreamField([('text', wagtail.core.blocks.CharBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('cta', wagtail.core.blocks.StructBlock([('button_page', wagtail.core.blocks.PageChooserBlock()), ('button_text', wagtail.core.blocks.CharBlock())]))], blank=True, null=True),
        ),
    ]
