# Generated by Django 3.2.4 on 2021-06-19 16:52

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0062_comment_models_and_pagesubscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogDetailPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('section1', wagtail.core.fields.StreamField([('title', wagtail.core.blocks.CharBlock()), ('date', wagtail.core.blocks.DateBlock())], blank=True, null=True)),
                ('section2', wagtail.core.fields.StreamField([('text', wagtail.core.blocks.TextBlock())], blank=True, null=True)),
                ('section3', wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock()), ('cards', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock()), ('text', wagtail.core.blocks.TextBlock())])))], blank=True, null=True)),
                ('section4', wagtail.core.fields.StreamField([('title', wagtail.core.blocks.CharBlock()), ('text', wagtail.core.blocks.TextBlock())], blank=True, null=True)),
                ('section5', wagtail.core.fields.StreamField([('part1', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock()), ('points', wagtail.core.blocks.ListBlock(wagtail.core.blocks.TextBlock()))]))])),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
