# Generated by Django 3.2.4 on 2021-06-19 17:04

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('blog_detail', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogdetailpage',
            name='section1',
            field=wagtail.core.fields.StreamField([('title', wagtail.core.blocks.CharBlock()), ('date', wagtail.core.blocks.DateBlock()), ('image', wagtail.images.blocks.ImageChooserBlock())], blank=True, null=True),
        ),
    ]
