# Generated by Django 3.2.4 on 2021-07-07 06:14

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog_detail', '0002_alter_blogdetailpage_section1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogdetailpage',
            name='section2',
            field=wagtail.core.fields.StreamField([('text', wagtail.core.blocks.RichTextBlock())], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blogdetailpage',
            name='section3',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock()), ('cards', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock()), ('text', wagtail.core.blocks.RichTextBlock()), ('cta', wagtail.core.blocks.StructBlock([('button_page', wagtail.core.blocks.PageChooserBlock()), ('button_text', wagtail.core.blocks.CharBlock())]))])))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blogdetailpage',
            name='section4',
            field=wagtail.core.fields.StreamField([('title', wagtail.core.blocks.CharBlock()), ('text', wagtail.core.blocks.RichTextBlock())], blank=True, null=True),
        ),
    ]
