# Generated by Django 3.2.4 on 2021-07-07 09:39

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog_detail', '0003_auto_20210707_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogdetailpage',
            name='section3',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock()), ('cards', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock()), ('text', wagtail.core.blocks.RichTextBlock()), ('cta', wagtail.core.blocks.StructBlock([('button_page', wagtail.core.blocks.PageChooserBlock(required=False)), ('button_text', wagtail.core.blocks.CharBlock(required=False))]))])))], blank=True, null=True),
        ),
    ]
