# Generated by Django 3.2.4 on 2021-07-06 10:21

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0062_comment_models_and_pagesubscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='SafeHelpfulPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('section1', wagtail.core.fields.StreamField([('heading_image', wagtail.images.blocks.ImageChooserBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('text_info', wagtail.core.blocks.TextBlock()), ('points', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock()), ('text', wagtail.core.blocks.CharBlock())]))), ('cta', wagtail.core.blocks.StructBlock([('button_page', wagtail.core.blocks.PageChooserBlock()), ('button_text', wagtail.core.blocks.CharBlock())]))], blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
