# Generated by Django 3.2.4 on 2021-06-17 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apppage',
            options={'verbose_name': 'App Page', 'verbose_name_plural': 'App Pages'},
        ),
    ]
