# Generated by Django 3.2.4 on 2021-07-06 17:57

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_apppage_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apppage',
            options={},
        ),
        migrations.RemoveField(
            model_name='apppage',
            name='page_heading',
        ),
        migrations.AddField(
            model_name='apppage',
            name='section2',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('cta', wagtail.core.blocks.StructBlock([('button_page', wagtail.core.blocks.PageChooserBlock()), ('button_text', wagtail.core.blocks.CharBlock())]))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='apppage',
            name='section1',
            field=wagtail.core.fields.StreamField([('banner_title', wagtail.core.blocks.CharBlock()), ('banner_image', wagtail.images.blocks.ImageChooserBlock())], blank=True, null=True),
        ),
    ]
