# Generated by Django 3.2.4 on 2021-07-04 12:50

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0062_comment_models_and_pagesubscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForIndividualsPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('section1', wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock()), ('text_info', wagtail.core.blocks.CharBlock()), ('cta', wagtail.core.blocks.StructBlock([('button_page', wagtail.core.blocks.PageChooserBlock()), ('button_text', wagtail.core.blocks.CharBlock())])), ('image', wagtail.images.blocks.ImageChooserBlock())], blank=True, null=True)),
                ('section2', wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock()), ('cards', wagtail.core.blocks.ListBlock(wagtail.images.blocks.ImageChooserBlock()))], blank=True, null=True)),
                ('section3', wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock()), ('cards', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('number', wagtail.core.blocks.IntegerBlock()), ('text_info', wagtail.core.blocks.TextBlock())])))], blank=True, null=True)),
                ('section4', wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock()), ('cards', wagtail.core.blocks.ListBlock(wagtail.images.blocks.ImageChooserBlock()))], blank=True, null=True)),
                ('section5', wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock()), ('reviews', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('review', wagtail.core.blocks.TextBlock()), ('person_name', wagtail.core.blocks.CharBlock()), ('person_info', wagtail.core.blocks.CharBlock()), ('person_image', wagtail.images.blocks.ImageChooserBlock())])))], blank=True, null=True)),
                ('section6', wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock()), ('text_info', wagtail.core.blocks.CharBlock()), ('cta', wagtail.core.blocks.URLBlock())], blank=True, null=True)),
                ('section7', wagtail.core.fields.StreamField([('heading1', wagtail.core.blocks.CharBlock()), ('heading2', wagtail.core.blocks.CharBlock()), ('text_info', wagtail.core.blocks.TextBlock()), ('cta', wagtail.core.blocks.StructBlock([('button_page', wagtail.core.blocks.PageChooserBlock()), ('button_text', wagtail.core.blocks.CharBlock())])), ('image', wagtail.images.blocks.ImageChooserBlock())], blank=True, null=True)),
                ('section8', wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock()), ('cards', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock()), ('content', wagtail.core.blocks.RichTextBlock()), ('cta', wagtail.core.blocks.StructBlock([('button_page', wagtail.core.blocks.PageChooserBlock()), ('button_text', wagtail.core.blocks.CharBlock())]))])))], blank=True, null=True)),
                ('section9', wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock()), ('cards', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock()), ('text', wagtail.core.blocks.CharBlock())])))], blank=True, null=True)),
                ('section10', wagtail.core.fields.StreamField([('cta', wagtail.core.blocks.StructBlock([('button_page', wagtail.core.blocks.PageChooserBlock()), ('button_text', wagtail.core.blocks.CharBlock())]))], blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
