# Generated by Django 3.2.4 on 2021-07-06 17:35

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0003_auto_20210617_1715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutuspage',
            name='page_heading',
        ),
        migrations.AddField(
            model_name='aboutuspage',
            name='section5',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock()), ('text_info', wagtail.core.blocks.RichTextBlock())], blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aboutuspage',
            name='section6',
            field=wagtail.core.fields.StreamField([('cta', wagtail.core.blocks.StructBlock([('button_page', wagtail.core.blocks.PageChooserBlock()), ('button_text', wagtail.core.blocks.CharBlock())]))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aboutuspage',
            name='section1',
            field=wagtail.core.fields.StreamField([('banner_title', wagtail.core.blocks.CharBlock()), ('banner_image', wagtail.images.blocks.ImageChooserBlock())], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aboutuspage',
            name='section2',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock()), ('cards', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock()), ('text', wagtail.core.blocks.CharBlock())])))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aboutuspage',
            name='section3',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock()), ('info_line', wagtail.core.blocks.CharBlock())], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aboutuspage',
            name='section4',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock()), ('cards', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('name', wagtail.core.blocks.CharBlock()), ('designation', wagtail.core.blocks.CharBlock())])))], blank=True, null=True),
        ),
    ]
